project:
  type: website

website:
  title: "blog"
  navbar:
    background: skyblue
    logo: ./img/school-locker.png
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jjyun98/R_locker/
      - icon: instagram
        href: https://instagram.com
  sidebar:
    style: "docked"
    search: true
    contents: auto

format:
  html:
    theme: Instance
    css: styles.css
    toc: true
    code-fold: false
    code-line-numbers: true
    code-copy: true

editor: visual