project:
  type: website

website:
  title: "Yun98"
  navbar: 
    background: brown
    logo: ./img/school-locker.png
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jjyun98/R_locker/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

